### ISSUE TITLE
Website: LEARN MORE link on frontpage(!) -> 404

### ISSUE THREAD

**Issue by COLABORATI** [liqd/adhocracy#960]
There is an I-can-not-believe-it error right on your frontdoor: besides the "Register" button there is a "LEARN MORE" that links to https://adhocracy.de/static/about_adhocracy.de - which is a 404. 

This is probably the first link any visitor that would like to learn something about your project will click, so letting this go into 404 has a very destructing effect on your project. Also it reduces the trust in your operations skills, as it would be expected to monitor or test such an important thing as your front site with any tool, so I think it would be wise to fix this link asap and work out any kind of website monitoring or a testing procedure that scans your site for such errors before going live.

BTW besides the Register link there is a german "oder" - this should be changed to an english "or" to demonstrate that your software is fully I18N capable.

**Comment by rukala** [comment]
Thank you very much for reporting the bug(s)!

Due to time constraints I managed to quickly fix the links. I closed the issue for now.

Thanks.
