### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by COLABORATI** [liqd/adhocracy#961]
Hi, I see several severe issues on your main website and I got the impression that the project might be dead? Do you need help?

**Comment by nidico** [comment]
> I got the impression that the project might be dead?

The project isn't dead, but development has shifted towards Adhocracy 3 ([repo](https://github.com/liqd/adhocracy3.mercator), [docs](https://adhocracy3mercator.readthedocs.org)). However this isn't ready for general consumption yet.

Adhocracy 2 (this repo) is mostly in bug-fixing mode. It's still in production in different places (e.g. currently [here](https://tempelhofer-feld.berlin.de/)), so bugs are fixed if relevant, but new development occurs almost exclusively in Adhocracy 3 for about a year.

> Do you need help?

Sure, help is always welcome. Adhocracy 3 development currently happens pretty much "behind closed doors" (or more concretely "in our office"), and we will need to spend some effort opening up the development and creating a community again. I'll expect that to happen in the next months.

Help with Adhocracy 2 is also welcome, e.g. bug fixes for things like #962.

Also feel free to engage with the (currently passive) mailing list [adhocracy-dev](http://lists.liqd.net/cgi-bin/mailman/listinfo/adhocracy-dev), which is supposed to be the mailing list for the adhocracy development community and will also be used to announce new developments and how to engage.

**Comment by COLABORATI** [comment]
Would you like to describe in a few short sentences what are the main differences between adhocracy 2 and the 3 version? Are there important changes in the model layer and backend that required a new repo? I am just reading into it, but of course a few introducing words could speed this process up.

Also it would be interesting to know what are your plans on supporting adhocracy 2? If I would like to use it for a project, which version should I use? 

It would be great if you would like to consider to release an official roadmap and a deprecation policy, like e.g. the django project does, what would be a great help for all projects considering to use adhocracy.
