### ISSUE TITLE
archive this project

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy#972]
I expect that no further work will be done on this repository. So I would like to ask to close all issues and pull request and mark it as [archived](https://help.github.com/articles/about-archiving-repositories/) .

My personal motivation for that is that it clutters my [issues](/issues) and [pull requests](/pulls). But I also think that it will help people to understand which projects are actually maintained.

**Comment by fuzzylogic2000** [comment]
Sounds good to me! What do you say, @MagdaN @treba123 ?

**Comment by nidico** [comment]
Okay for me!

**Comment by rmader** [comment]
Jep

**Comment by Chealer** [comment]
@xi , could you please explain why you expect that?

**Comment by fuzzylogic2000** [comment]
@Chealer The last commit was 2016 and noone is maintaining this project. We are currently working on [adhocracy4](https://github.com/liqd/adhocracy4).
